// Code generated by mockery v1.0.0

package mocks

import mock "github.com/stretchr/testify/mock"

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: src, msg
func (_m *Handler) Handle(src interface{}, msg interface{}) error {
	ret := _m.Called(src, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) error); ok {
		r0 = rf(src, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
