// Code generated by mockery v1.0.0

package mocks

import mock "github.com/stretchr/testify/mock"
import xmpp "github.com/KurioApp/gcm-xmpp"

// XMPPClientFactory is an autogenerated mock type for the XMPPClientFactory type
type XMPPClientFactory struct {
	mock.Mock
}

// NewXMPPClient provides a mock function with given fields: host, user, passwd
func (_m *XMPPClientFactory) NewXMPPClient(host string, user string, passwd string) (xmpp.XMPPClient, error) {
	ret := _m.Called(host, user, passwd)

	var r0 xmpp.XMPPClient
	if rf, ok := ret.Get(0).(func(string, string, string) xmpp.XMPPClient); ok {
		r0 = rf(host, user, passwd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(xmpp.XMPPClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(host, user, passwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
